FUNDINGLIST
—create
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO) 
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-27',1,1,11,1);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-28',2,2,12,2);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-27',3,3,13,3);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-05-05',4,4,14,4);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-29',5,5,15,5);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-05-10',6,6,16,6);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-05-01',7,7,17,7);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-29',8,8,18,8);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-30',9,9,19,9);
INSERT INTO FUNDINGLIST(FL_NO, FL_DATE, USER_NO, CARD_NO, FUNDING_NO, MOVIE_NO)
VALUES (FUNDINGLIST_FL_NO_SEQ.nextval,'2021-04-27',10,10,20,10);

—펀딩 상태 변경
UPDATE FUNDINGLIST SET FL_STATUS = '성공' WHERE FL_NO = 3;
—펀딩리스트 삭제
DELETE FROM FUNDINGLIST WHERE FL_NO = 2;
—펀딩정보찾기
SELECT FL_NO, FL_DATE, FL_STATUS FROM FUNDINGLIST WHERE FL_NO = '3';
